name: Docs

on:
  push:
    branches:
    - main
    paths:
    - src/**
    - docfx/**
    - .github/workflows/docs.yml
  pull_request:
    branches:
    - main
    paths:
    - docfx/**
    - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  generate-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install and Build
      run: |
        curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o docfx.zip
        unzip -d .docfx docfx.zip
        dotnet ./.docfx/docfx.exe docfx/docfx.json

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docfx/_site # The folder the action should deploy.
