name: Docs

on:
  push:
    branches:
    - main
    paths:
    - src/**
    - docfx/**
    - .github/workflows/docs.yml
  pull_request:
    branches:
    - main
    paths:
    - docfx/**
    - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  generate-docs:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx

    - name: DocFX Build
      working-directory: docs
      run: docfx docfx/docfx.json
      continue-on-error: false

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docfx/_site # The folder the action should deploy.
